export const recTypeToGenre: Record<string, string> = {
  action_recs: "Action",
  adventure_recs: "Adventure",
  anime_series_international_tv_shows_recs:
    "Anime Series International TV Shows",
  british_tv_shows_docuseries_international_tv_shows_recs:
    "British TV Shows Docuseries International TV Shows",
  children_recs: "Children",
  comedies_recs: "Comedies",
  comedies_dramas_international_movies_recs:
    "Comedies Dramas International Movies",
  comedies_international_movies_recs: "Comedies International Movies",
  comedies_romantic_movies_recs: "Comedies Romantic Movies",
  crime_tv_shows_docuseries_recs: "Crime TV Shows Docuseries",
  documentaries_international_movies_recs: "Documentaries International Movies",
  docuseries_recs: "Docuseries",
  dramas_recs: "Dramas",
  dramas_international_movies_recs: "Dramas International Movies",
  dramas_romantic_movies_recs: "Dramas Romantic Movies",
  family_movies_recs: "Family Movies",
  fantasy_recs: "Fantasy",
  horror_movies_recs: "Horror Movies",
  international_movies_thrillers_recs: "International Movies Thrillers",
  international_tv_shows_romantic_tv_shows_tv_dramas_recs:
    "International TV Shows Romantic TV Shows TV Dramas",
  kids_tv_recs: "Kids' TV",
  language_tv_shows_recs: "Language TV Shows",
  musicals_recs: "Musicals",
  nature_tv_recs: "Nature TV",
  reality_tv_recs: "Reality TV",
  spirituality_recs: "Spirituality",
  tv_action_recs: "TV Action",
  tv_comedies_recs: "TV Comedies",
  tv_dramas_recs: "TV Dramas",
  talk_shows_tv_comedies_recs: "Talk Shows TV Comedies",
  thrillers_recs: "Thrillers",
};
